- name: Linux Server Health Check
  hosts: all
  gather_facts: no
  become: yes

  tasks:
    - name: Check Uptime
      ansible.builtin.command: uptime -p
      register: uptime_result

    - name: Check CPU Load
      ansible.builtin.command: uptime
      register: cpu_load

    - name: Check Memory Usage
      ansible.builtin.shell: |
        free -m | awk 'NR==2{printf "Memory Usage: %s/%sMB (%.2f%%)\n", $3, $2, $3*100/$2 }'
      register: mem_usage

    - name: Check Disk Space
      ansible.builtin.shell: |
          df -h | awk '$NF=="/"{printf "Disk Usage: %d/%dGB (%s)", $3,$2,$5}'
      register: disk_usage

    - name: Check Running Services
      ansible.builtin.systemd:
        name: sshd
      register: ssh_status

    - name: Display Server Health Report
      ansible.builtin.debug:
        msg:
          - "🖥️  Host: {{ inventory_hostname }}"
          - "⏳ Uptime: {{ uptime_result.stdout }}"
          - "💾 {{ mem_usage.stdout }}"
          - "📀 {{ disk_usage.stdout }}"
          - "🔥 CPU Load: {{ cpu_load.stdout_lines[0] }}"
          - "🔍 SSH Service: {{ 'Running' if ssh_status.status.ActiveState == 'active' else 'Stopped' }}"
