- name: Check nagent service status
  hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: Check if nagent service exists
      ansible.builtin.shell: |
        systemctl status nagent.service
      register: nagent_status
      changed_when: false
      failed_when: "'Active: active (running)' not in nagent_status.stdout"

    - name: Display nagent service full status
      ansible.builtin.debug:
        var: nagent_status.stdout_lines
